---
- name: Update all Linux hosts
  hosts: k8s:lutil
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
