---
- name: Forcefully restart Windows servers
  hosts: ad:wutil:general
  gather_facts: false

  tasks:
    - name: Gather facts
      setup:

    - name: Ensure the target hosts are Windows
      assert:
        that:
          - ansible_os_family == "Windows"
        fail_msg: "This playbook is only intended for Windows hosts."

    - name: Forcefully restart Windows servers
      win_shell: |
        Restart-Computer -Force
