---
- name: Setup Secondary Windows Domain Controller (Existing Forest/Domain)
  hosts: "*-ad-2a"
  gather_facts: false
  tasks:
    - name: Gather facts
      setup:

    - name: Set Local Administrator Password
      win_user:
        name: Administrator
        password: "{{ ansible_password }}"
        state: present

    - name: Disable Defrag
      win_scheduled_task:
        path: "\\Microsoft\\Windows\\Defrag"
        name: "ScheduledDefrag"
        enabled: false

    - name: Stop Windows Update, Just in Case
      win_service:
        name: wuauserv
        state: stopped

    - name: Set DNS to the First DC
      win_dns_client:
        adapter_names:
          - "*"
        ipv4_addresses:
        - "{{ hostvars[groups['ad'] | select('search', 'ad-1a$') | list | first | default('')]['ansible_host'] | default('') }}"

    - name: Disable Windows Firewall With Scheduled Task
      win_shell: |
        $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument 'Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False'
        $trigger = New-ScheduledTaskTrigger -AtStartup
        $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest
        Register-ScheduledTask -TaskName "DisableFirewallOnStartup" -Action $action -Trigger $trigger -Principal $principal -Force
      args:
        executable: powershell.exe

    - name: Promote Server to Additional Domain Controller
      microsoft.ad.domain_controller:
        domain_admin_user: "{{ ansible_domain_prefix }}\\{{ ansible_user }}"
        domain_admin_password: "{{ ansible_password }}"
        dns_domain_name: "{{ ansible_env_fqdn }}"
        safe_mode_password: "{{ ansible_password }}"
        install_dns: true
        database_path: "C:\\Windows\\NTDS"
        sysvol_path: "C:\\Windows\\SYSVOL"
        state: "domain_controller"
        reboot: true
      register: dc_promoted
      retries: 3
      delay: 30
      until: dc_promoted is succeeded

    - name: Remove the scheduled task to disable firewall
      win_scheduled_task:
        name: "DisableFirewallOnStartup"
        state: absent
        
    - name: Set DNS servers
      win_dns_client:
        adapter_names:
          - "*"
        ipv4_addresses:
          - 127.0.0.1
          - "{{ hostvars[groups['ad'] | select('search', 'ad-1a$') | list | first | default('')]['ansible_host'] | default('') }}"