---
- name: Forcefully shut down Windows servers
  hosts: ad:wutil:general
  gather_facts: false

  tasks:
    - name: Gather facts
      setup:

    - name: Ensure the target hosts are Windows
      assert:
        that:
          - ansible_os_family == "Windows"
        fail_msg: "This playbook is only intended for Windows hosts."

    - name: Forcefully shut down Windows servers
      win_shell: |
        Stop-Computer -Force
